[metadata]
name = anybooru
version = 0.1.0.dev1
description = A package to access Danbooru/Moebooru/Serika/e621ng/Zerochan/Gelbooru/Gelbooru02/Shuushuu/Sakuria APIs
url = https://github.com/NebulaeWisdom/anybooru
license = MIT License
author = NebulaeWisdom
author_email = rezerols@gmail.com
project_urls =
    Documentation = https://github.com/NebulaeWisdom/anybooru/tree/master/docs
    Source = https://github.com/NebulaeWisdom/anybooru
    Issues = https://github.com/NebulaeWisdom/anybooru/issues
    Changelog = https://github.com/NebulaeWisdom/anybooru/blob/master/changelog.md
keywords = moebooru, danbooru, serika, e621, e926, zerochan, gelbooru, gelbooru02, tbib, shuushuu, sakuria, pixiv, API, client
classifiers =
    Development Status :: 5 - Production/Stable
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Internet
    Topic :: Internet :: WWW/HTTP :: Site Management
platforms = any
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
license_files = LICENSE

[options]
packages = anybooru
install_requires =
    requests >= 2.26
python_requires = >= 3.6
include_package_data = True

[options.package_data]
anybooru = anybooru.json
